apiVersion: v1
kind: PersistentVolume
metadata:
  name: day55-pv
spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /tmp/k8s-pv-data
    type: DirectoryOrCreate
